---
apiVersion: v1
kind: pod
metadata: 
  name: alp
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerport: 80
    - name: alp-1
      image: alpine
      ports:
        - containerport: 80
      args:
        - sleep
        - 1d
